### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by salmenf** [webwriter-app/webwriter#36]
**Rich text features** ([GFM Support](https://github.github.com/gfm/))

*Inline*
  - [ ] Backslash escapes (?)
  - [x] Entity and numeric character references -> not neccessary
  - [x] Emphasis and strong emphasis
  - [x] Strikethrough
  - [x] Links
  - [ ] Autolinks
  - [ ] Raw HTML

*Leaf*
  - [ ] Thematic break
  - [ ] Headings (implement as mark?)
  - [x] Code block = `ww-code`
  - [ ] Footnotes
  - [ ] Raw HTML

*Container*
  - [ ] Tables
  - [ ] Block quotes
  - [ ] Unordered/Ordered/Task Lists

**Multimedia features**
- [ ] Picture
- [ ] Audio
- [ ] Video
- [ ] Link/Website
- [ ] Code

**H5P features**
- [ ] Generic H5P content type support
