### ISSUE TITLE
CSS Roadmap

### ISSUE THREAD

**Issue by salmenf** [webwriter-app/webwriter#42]
*Inline attributes* (Mark)
  - [ ] Backslash escapes (?)
  - [x] Entity and numeric character references -> not neccessary
  - [x] Emphasis and strong emphasis
  - [x] Strikethrough
  - [x] Links
  - [ ] Autolinks
  - [ ] Raw HTML
  - [x] Font Size
  - [x] Font Family
  - [ ] Font Color
  - [ ] Font Background Color
  - [x] Sup/Sub

*Block attributes*
  - [x] Justify
  - [ ] Line height
  - [ ] Margins
