### ISSUE TITLE
H5P Support Roadmap

### ISSUE THREAD

**Issue by salmenf** [webwriter-app/webwriter#43]

**Comment by salmenf** [comment]
PhET Support
- [ ] Start screen: Name to dropdown
- [ ] Toolbar: Name to dropdown
- [ ] Remember settings
- [ ] Remember simulation state
